### ISSUE TITLE
"MVPリリース"レビュー依頼

### ISSUE THREAD

**Issue by meg-06** [meg-06/yubimoji#58]
## 各種情報
サービス名：ゆびもじ
サービスURL：https://yubimoji.onrender.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] 会員登録
- [x] ログイン
- [x] 入力した日本語が指文字に変換される機能
- [ ] お気に入り登録・解除
- [x] 登録した単語一覧

## READMEレビュー時から変更した機能
- [ ] お気に入り登録・解除
上記の機能はMVPリリース後に実装予定です。

## サービスイメージがわかるようなスクリーンショット等

![Image](https://github.com/meg-06/yubimoji/assets/143862035/f13ec608-c745-4df6-abac-e97060ff9db7)
![Image](https://github.com/meg-06/yubimoji/assets/143862035/65c200f6-f34d-4e6d-9732-f6ff692a1d45)
![Image](https://github.com/meg-06/yubimoji/assets/143862035/df8efadc-810f-41d8-bee0-74eb5a388927)
![Image](https://github.com/meg-06/yubimoji/assets/143862035/7f263f52-e5d7-4ebc-87ac-e291b51557a4)
![Image](https://github.com/meg-06/yubimoji/assets/143862035/3b75469f-0a36-4e48-94d4-82a8dcc03b97)
![Image](https://github.com/meg-06/yubimoji/assets/143862035/395de083-55d4-400a-a217-db94a0e9d55e)
![Image](https://github.com/meg-06/yubimoji/assets/143862035/b31755c7-836c-4e0b-b112-d219c7f422f2)

**Comment by kenchasonakai** [comment]
LGTMです！
