### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by meg-06** [meg-06/yubimoji#6]
### 実装予定の機能
- [ ] 会員登録
- [ ] 入力した日本語が指文字に変換される機能
- [ ] お気に入り登録
- [ ] お気に入り解除
- [ ] 登録した単語一覧

### 必要なページ
- [ ] トップページ
- [ ] 会員登録
- [ ] ログイン
- [ ] マイページ
- [ ] 日本語登録画面
- [ ] 単語一覧
- [ ] お気に入り一覧
- [ ] 指文字再生画面
- [ ] 会員登録情報

**Comment by Tsuchiya2** [comment]
ご提出ありがとうございます。
以下コメントになります。

---

・デプロイ、rails newなどのカードも作成しましょう。
・外部APIや技術に関して調査するものがあれば、それもカードを用意しましょう。

また、ストーリーポイント5を付けているカードですが、初めて取り組むものや見通しが立っていないものにポイント5を付けているように見受けられました。ストーリーポイント1,2になるまで細分化することで、分かっている箇所、不透明な箇所が可視化されますし、進捗を感じながら開発を進めることができます。

**Comment by meg-06** [comment]
> ご提出ありがとうございます。 以下コメントになります。
> 
> ・デプロイ、rails newなどのカードも作成しましょう。 ・外部APIや技術に関して調査するものがあれば、それもカードを用意しましょう。
> 
> また、ストーリーポイント5を付けているカードですが、初めて取り組むものや見通しが立っていないものにポイント5を付けているように見受けられました。ストーリーポイント1,2になるまで細分化することで、分かっている箇所、不透明な箇所が可視化されますし、進捗を感じながら開発を進めることができます。

返信いただきありがとうございます。
アドバイスをいただいた通りに以下の２点を変更しました。APIについては、現時点で使用する予定が無いためカードを追加していません。ご確認いただけると幸いです。

- デプロイやrails newのカードを追加しました
- ストーリーポイント5のものを削除しました

**Comment by tmtkzk0823** [comment]
修正ありがとうございます。
概ね良さそうです。
LGTMです！
